FROM debian:stretch
RUN apt-get update

# (1) Install MRTrix
#   - IMPORTANT: use only 1 CPU, but increase Docker RAM usage to 5 GB for installation
# Clone Git and get dependencies
RUN apt-get install -y git g++ python python-numpy libeigen3-dev zlib1g-dev libqt4-opengl-dev libgl1-mesa-dev libfftw3-dev libtiff5-dev
RUN git clone https://github.com/MRtrix3/mrtrix3.git
RUN cd mrtrix3 && ./configure && ./build && ./set_path

# (2) Install FSL 
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    gcc \
    git \
    python-pip \
    python2.7 \
    python2.7-dev \
    python-tk \
    ssh \
    wget \
    && apt-get autoremove \
    && apt-get clean

RUN pip install -U "setuptools" "pip"
RUN pip install -U "matplotlib==2.1.1" "nibabel==2.2.1" "numpy==1.13.3" "scipy==1.0.0" "scikit-image==0.13.1" \
    "docopt==0.6.2" "pandas==0.22.0"

RUN wget http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py \
    && python fslinstaller.py -E -V 5.0.10 -d /usr/local/fsl \
    && rm fslinstaller.py \
    && rm fsl.csh \
    && rm fsl.sh

# Manually set up the FSL environment, since the fsl.sh script generated by the fslinstaller.py is broken
ENV PATH /usr/local/fsl/bin:/usr/local/fsl/lib:$PATH
ENV FSLDIR /usr/local/fsl
ENV FSLOUTPUTTYPE NIFTI_GZ
ENV FSLMULTIFILEQUIT TRUE
ENV FSLPARALLEL 1
ENV SGE_ON false

ENTRYPOINT ["/bin/bash"]

